name: End-to-end tests
on: [push]
jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn Install

      - name: Run linter
        run: yarn lint

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: yarn build
          start: yarn serve
          wait-on: http://localhost:8080